name: uni_ya_control
description: Uni Ya Control

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.6
  hive:
  hive_flutter:
  uuid: ^3.0.7
  flutter_easyloading: ^3.0.5
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  firebase_storage: ^11.0.8
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.2.16
  carousel_slider: ^4.2.1
  flutter_zoom_drawer: ^3.0.3
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.2.4
  flutter_slidable: ^2.0.0
  badges: ^2.0.3
  flutter_local_notifications: ^13.0.0
  firebase_messaging: ^14.2.1
  http: ^0.13.5
  dio: ^4.0.6
  awesome_notifications: ^0.7.4+1
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:
  flutter_launcher_icons: "^0.13.0"
#
#flutter_native_splash:
#  color: "#000000"
#  image: assets/images/splash.jpg
#  android_12:
#
#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo.jpg"
#  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/illustrations/
